<?php
/*$server="localhost";
error_reporting(-1);
$username="id5114574_iamrohitsuthar";
$pwd="rs0t000!";
$dbname="id5114574_mydb";*/
$server="localhost";
//error_reporting(-1);
$username="root";
$pwd="";
$dbname="portfolio";
$conn=mysqli_connect($server,$username,$pwd,$dbname);
?>